baseURL: "https://learn.scientific-python.org/"
title: "Learn Scientific Python"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false

params:
  description: "Documentation for the Scientific Python community."
  images:
  - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Learn Scientific Python
    link: /
  hero:
    title: Learn Scientific Python
    image: logo.svg
  navbar:
   - title: User Guide
     url: /users/
   - title: Contributor Guide
     url: /contributors/
   - title: Maintainer Guide
     url: /maintainers/
  panel:
    title: The definitive documentation
    subtitle: by the community, for the community
    tiles:
    - buttonText: User Guide
      url: /users/
      text: Learn how to make the most of the Scientific Python ecosystem.
    - buttonText: Contributor Guide
      url: /contributors/
      text: Learn best-practices for contributing to Scientific Python.
    - buttonText: Maintainer Guide
      url: /maintainers/
      text: Learn how to build, coordinate, and sustain a healthy project.
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://scientific-python.org/
        icon: scientific-python
      - link: https://discuss.scientific-python.org/
        icon: discourse
      - link: https://github.com/scientific-python/learn.scientific-python.org
        icon: github
    quicklinks:
      column1:
        title: ""
        links:
          - text: Code of Conduct
            link: https://scientific-python.org/code_of_conduct/
      column2:
        links:
      column3:
        links:
