baseURL: "https://learn.scientific-python.org/"
title: "Learn"
theme: scientific-python-hugo-theme
disableKinds: ["term", "taxonomy"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        enableDefault: true

params:
  description: "Documentation for the Scientific Python community."
  images:
    - /images/logo.svg
  navbarlogo:
    image: logo.svg
    text: Learn Scientific Python
    link: /
  navbar:
    - title: Home
      url: https://scientific-python.org/
    - title: Blog
      url: https://blog.scientific-python.org
    - title: Learn
      url: /
    - title: Tools
      url: https://tools.scientific-python.org
  footer:
    logo: logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/scientific-python/
        icon: github
      - link: https://www.youtube.com/c/ScientificPython-org
        icon: youtube
      - link: https://fosstodon.org/@scientific_python
        icon: mastodon
      - link: https://discuss.scientific-python.org
        icon: discourse
      - link: https://discord.com/invite/vur45CbwMz
        icon: discord

    quicklinks:
      column1:
        title: ""
        links:
          - text: About
            link: /about/
          - text: Roadmap
            link: /roadmap/
          - text: Code of Conduct
            link: https://scientific-python.org/code_of_conduct/
      column2:
        title: "Maintainers"
        links:
          - text: SPECs
            link: https://scientific-python.org/specs/
          - text: Summits
            link: https://scientific-python.org/summits/
          - text: Calendars
            link: https://scientific-python.org/calendars/
      column3:
        links:
          - text: Press kit
            link: https://scientific-python.org/press-kit/
